#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys
import json
import subprocess


PROJECT_TYPE = 'casperjs'
SPIDERS_PATH = '/app'


def list_spiders():
    return next(os.walk(SPIDERS_PATH))[2]


def get_debug_info():
    entries = [
        ('CasperJS version', os.getenv('CASPERJS_VERSION')),
        ('PhantomJS version', os.getenv('PHANTOMJS_VERSION')),
        ('Linux packages', subprocess.check_output(['dpkg', '-l'])),
    ]
    return u'\n'.join(
        u'{}:\n {}\n'.format(title, data) for title, data in entries
    )


def main():
    data = {
        'project_type': PROJECT_TYPE,
        'spiders': list_spiders(),
    }
    if '--debug' in sys.argv:
        data['debug'] = get_debug_info()
    print(json.dumps(data))


if __name__ == '__main__':
    main()
